// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOBHcoORCUe3iNDkIl4JBjIkcdeRaQE3w',
    appId: '1:1027841119250:web:a84664d7d14f8fcd4774cb',
    messagingSenderId: '1027841119250',
    projectId: 'lod-db',
    authDomain: 'lod-db.firebaseapp.com',
    databaseURL: 'https://lod-db-default-rtdb.firebaseio.com',
    storageBucket: 'lod-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVIq_Dte-y9EgABirHg5mLpY_qx2QTPek',
    appId: '1:1027841119250:android:e4185d1ca86d1bfd4774cb',
    messagingSenderId: '1027841119250',
    projectId: 'lod-db',
    databaseURL: 'https://lod-db-default-rtdb.firebaseio.com',
    storageBucket: 'lod-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJJxQit0ufTgPPBCvvRjderTq6Cmr7cQ',
    appId: '1:1027841119250:ios:62cde8b93158af084774cb',
    messagingSenderId: '1027841119250',
    projectId: 'lod-db',
    databaseURL: 'https://lod-db-default-rtdb.firebaseio.com',
    storageBucket: 'lod-db.firebasestorage.app',
    iosBundleId: 'com.example.lodGui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrJJxQit0ufTgPPBCvvRjderTq6Cmr7cQ',
    appId: '1:1027841119250:ios:62cde8b93158af084774cb',
    messagingSenderId: '1027841119250',
    projectId: 'lod-db',
    databaseURL: 'https://lod-db-default-rtdb.firebaseio.com',
    storageBucket: 'lod-db.firebasestorage.app',
    iosBundleId: 'com.example.lodGui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOBHcoORCUe3iNDkIl4JBjIkcdeRaQE3w',
    appId: '1:1027841119250:web:9a116d5240fc7b3a4774cb',
    messagingSenderId: '1027841119250',
    projectId: 'lod-db',
    authDomain: 'lod-db.firebaseapp.com',
    databaseURL: 'https://lod-db-default-rtdb.firebaseio.com',
    storageBucket: 'lod-db.firebasestorage.app',
  );

}